import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { StrictMode } from "react";
import ReactDOM from "react-dom/client";
import { createBrowserRouter, createRoutesFromElements, Route, RouterProvider, } from "react-router-dom";
import App from "./App";
import Home from "./routes/Home";
import Profile from "./routes/Profile";
const root = ReactDOM.createRoot(document.querySelector("body"));
const profileLoader = () => fetch("https://jsonplaceholder.typicode.com/users");
const router = createBrowserRouter(createRoutesFromElements(_jsxs(Route, { path: "/odin-waldo/", element: _jsx(App, {}), children: [_jsx(Route, { path: "/odin-waldo/", element: _jsx(Home, {}) }), _jsx(Route, { path: "/odin-waldo/app", element: _jsx("div", {}) }), _jsx(Route, { loader: profileLoader, path: "/odin-waldo/profile", element: _jsx(Profile, {}) })] })));
root.render(_jsx(StrictMode, { children: _jsx(RouterProvider, { router: router }) }));
